"""Add Grupo model and relationship to Receta

Revision ID: 65b880ef501d
Revises: b29f7ae8b140
Create Date: 2025-09-18 21:49:03.330269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65b880ef501d'
down_revision = 'b29f7ae8b140'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    if '_alembic_tmp_modelo_ipv' in inspector.get_table_names():
        op.drop_table('_alembic_tmp_modelo_ipv')

    with op.batch_alter_table('modelo_ipv', schema=None) as batch_op:
        batch_op.drop_column('comentario')

    with op.batch_alter_table('recetas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grupo_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key('fk_recetas_grupo_id', 'grupos', ['grupo_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recetas', schema=None) as batch_op:
        batch_op.drop_constraint('fk_recetas_grupo_id', type_='foreignkey')
        batch_op.drop_column('grupo_id')

    with op.batch_alter_table('modelo_ipv', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comentario', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
